In [103]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.11.0


In [104]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [105]:
#check no of dimensions of a tensor NDIM 
scalar.ndim

0

In [106]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [107]:
#checking dimesions of vector
vector.ndim

1

In [108]:
#create a matrix (more than one dimensions)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [109]:
matrix.ndim

2

In [110]:
#create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) #specifying the data type of our matrix
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [111]:
another_matrix.ndim

2

In [112]:
#lets create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6,]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [113]:
tensor.ndim

3

<h2>Creating tensors with tf.variable</h2>

In [114]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [115]:
#trying to change the variables
# changable_tensor[0] = 7
# changable_tensor

In [116]:
#lets try the assign fxn
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [117]:
#change unchangable tensor
# unchangable_tensor[0].assign(7)
# unchangable_tensor

we cant change constant tensors!

<h2>Creating random tensors<h2>

random tensors are tensors of some arbitrary size which contain random numbers

In [118]:
#create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproduciblity
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42) #set seed for reproduciblity
random_2 = random_2.normal(shape = (3,2))

#are they equal?
random_1, random_2 , random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffling the order of elements in a tensor

In [119]:
#Shuffle a tensor
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
#Shuffling
#to get a seeded random shuffle, we need a global level seed and an operational seed
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled,seed=42) #operational level seed
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

Other ways to make tensors

In [120]:
#create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [121]:
#create a tensor of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [122]:
#We can turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) #create a numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) #capital for matrix or tensor
# y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [123]:
A = tf.constant(numpy_A,shape=(2,3,4))
#remember that the dimensions shld mul upto the  number of elements in the numpy array
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

<h2>Getting Information from Tensors</h2>

In [124]:
#create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [125]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [126]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [127]:
print("Datatype of every element: ",rank_4_tensor.dtype)
print("Number of dimensions [rank]: ",rank_4_tensor.ndim)
print("Shape of the tensor: ",rank_4_tensor.shape)
print("Elements along the 0 axis: ",rank_4_tensor.shape[0])
print("Elements along the last axis: ",rank_4_tensor.shape[-1])
print("Total number of elements in the tensor: ",tf.size(rank_4_tensor))
print("Total number of elements in the tensor: ",tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions [rank]:  4
Shape of the tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in the tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in the tensor:  120


<h2>Indexing Tensors</h2>

In [128]:
#get the first two elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [131]:
#Get first element from each index except the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [134]:
#create a rank two tensor (2 dimension)
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.ndim

2

In [135]:
#get the last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [136]:
#add extra dimension to tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [137]:
#alternative
tf.expand_dims(rank_2_tensor,axis=-1) #-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [138]:
#expand 0 axis
tf.expand_dims(rank_2_tensor,axis=0) #0 means expand the first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [139]:
#expand middle axis or 1 axis
tf.expand_dims(rank_2_tensor,axis=1) #1 means expand the middle axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

<h2>Manipulating tensors</h2>

In [141]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10 #adds 10 to every element

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [142]:
#original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [143]:
#Can be applied to mul, sub also
#We can use built in fxn too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

<h3>Matrix Multiplication</h3>

In [144]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [145]:
#with python operator "@"
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [146]:
tensor.shape

TensorShape([2, 2])

In [149]:
#create tensor of (3,2)
X = tf.constant([[1,2],
                 [3,4],
                 [3,2]])
#create another (3,2) tensor
Y = tf.constant([[7,8],
                [9,10],
                [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [3, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [151]:
#For multiplication the number of rows in first mat should be equal to number of columns in second matrix
#3x2 3x2 wont work as 3 != 2
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [161]:
#changing shape of Y
Y = tf.reshape(Y,shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [163]:
#Now multiply
tf.matmul(X,tf.reshape(Y,shape=[2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[27, 30, 33],
       [61, 68, 75],
       [41, 46, 51]], dtype=int32)>

In [165]:
#resulting matrix is 3x3 size

In [167]:
#can do the same with transpose
X,tf.transpose(X), tf.reshape(X,shape=[2,3])

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [3, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 3],
        [2, 4, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 3, 2]], dtype=int32)>)

In [170]:
#try multiplicating transpose rather than reshape
tf.matmul(tf.transpose(X),tf.transpose(Y)) #used transpose in Y as it was reshaped earlier

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[58, 79],
       [64, 88]], dtype=int32)>

In [171]:
#dot product
X = tf.constant([[1,2],
                 [3,4],
                 [3,2]])
#create another (3,2) tensor
Y = tf.constant([[7,8],
                [9,10],
                [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [3, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [173]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[67, 74],
       [72, 80]], dtype=int32)>

In [175]:
#transpose and matmul have different results!
tf.matmul(X,tf.transpose(Y)),tf.matmul(X,tf.reshape(Y,shape=[2,3]))

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[23, 29, 35],
        [53, 67, 81],
        [37, 47, 57]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[27, 30, 33],
        [61, 68, 75],
        [41, 46, 51]], dtype=int32)>)

In [178]:
print("Normal Y: ")
print(Y)
print("Transpose Y: ")
print(tf.transpose(Y))
print("Reshaped Y: ")
print(tf.reshape(Y,shape=[2,3]))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Transpose Y: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
Reshaped Y: 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


generally we will be doing the transpose rather than the reshaping

<h2>Changing Data Type of Tensor</h2>

default is int32.
We can change data types through tf.cast

In [179]:
#create a new tensor with default datatype (float 32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [180]:
#change from float32 to float16
B = tf.cast(B,dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [183]:
#change from int32 to float32
C = tf.constant([2,7])
C = tf.cast(C,dtype = tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 7.], dtype=float32)>

<h2>Aggregating Tensors</h2>

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [186]:
#get the absolute values
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [211]:
Z  =tf.constant(np.random.randint(0,100,size=50))

#getting the minimum of a matrix
tf.reduce_min(Z)

#getting the maximum of a tensor
tf.reduce_max(Z) 

#getting the mean of a tensor
tf.reduce_mean(Z)

#getting the sum of a tensor
tf.reduce_sum(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=2497>

In [220]:
#finding variance of a tensor
Z = tf.cast(Z,dtype=tf.float32)
tf.math.reduce_variance(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=996.8965>

In [221]:
#Finding the standard deviation of tensor
tf.math.reduce_std(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=31.573668>

In [264]:
#finding positional maximum and minimum
tf.random.set_seed(43)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
       0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
       0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
       0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
       0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
       0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
       0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
       0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
       0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
       0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ],
      dtype=float32)>

In [267]:
tf.math.argmax(F) #Returns the index with the largest value across axes of a tensor.

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [268]:
tf.math.argmin(F) #Returns the index with the smallest value across axes of a tensor.

<tf.Tensor: shape=(), dtype=int64, numpy=32>

<h1>Squeezing a tensor(removing all single dimensions)</h1>

In [280]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [281]:
G.shape

TensorShape([1, 1, 1, 50])

In [285]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

<h2>One hot encoding</h2>

In [286]:
#create a list of indices
some_list = [0,1,2,3] #could be red,green, blue and purple

#one_hot encoding
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [289]:
#specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="ON", off_value="OFF")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

Squaring, log and square root

In [291]:
#create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [292]:
#squaring it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [298]:
#square rooting it
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [299]:
#finding log of H
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

<h1>Tensors and NumPy</h1>

In [302]:
#create a tensor directly from numpy array
J = tf.constant(np.array([3.,7.,5.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 7., 5.])>

In [304]:
#tensor to numpy
np.array(J), type(np.array(J))

(array([3., 7., 5.]), numpy.ndarray)

In [305]:
#tensor to numpy
J.numpy(),type(J.numpy())

(array([3., 7., 5.]), numpy.ndarray)

In [307]:
#default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

#check datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

Finding access to GPUs

In [308]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]